version: "3.7"
services:
  database:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "test-sharing-vision"
      MYSQL_USER: "julian"
      MYSQL_PASSWORD: "1i2r3e4a"
      MYSQL_ROOT_PASSWORD: "1i2r3e4a"
    ports:
      - "3306:3306"
  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - database
